export const basicSciencesStructure = {
  Hematology: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  Cardiovascular: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  NervousSystem: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  Gastrointestinal: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  ImmuneSystem: [
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  RenalSystem: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  RespiratorySystem: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  ReproductiveSystem: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  EndocrineSystem: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  MusculoskeletalSystem: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
  IntegumentarySystem: [
    'Anatomy',
    'Physiology',
    'Biochemistry',
    'Genetics',
    'Imaging',
    'Immunology',
    'Microbiology',
    'Histology',
    'Pathology',
    'Pharmacology',
    'Cellular biology',
    'Biostatistics',
  ],
};

export type BasicSciencesStructureType = typeof basicSciencesStructure; 